// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationWithMySql.DAL;

namespace MigrationWithMySql.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MigrationWithMySql.Models.AddressType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(60);

                    b.Property<string>("AddressTitle")
                        .HasMaxLength(120);

                    b.Property<string>("City")
                        .HasMaxLength(30);

                    b.Property<string>("Country")
                        .HasMaxLength(20);

                    b.Property<string>("Fax")
                        .HasMaxLength(25);

                    b.Property<string>("Phone")
                        .HasMaxLength(25);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15);

                    b.Property<string>("Region")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("AddressType");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.Company", b =>
                {
                    b.Property<long>("CompanyID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AddressId");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<long?>("PrimaryContactContactID");

                    b.Property<string>("Web")
                        .HasMaxLength(100);

                    b.HasKey("CompanyID");

                    b.HasIndex("AddressId");

                    b.HasIndex("PrimaryContactContactID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CompanyID");

                    b.Property<double>("Discount");

                    b.Property<double>("Freight");

                    b.Property<DateTime>("OrderDate");

                    b.Property<long?>("PersonContactContactID");

                    b.Property<long?>("ShipCompanyCompanyID");

                    b.Property<DateTime?>("ShipDate");

                    b.HasKey("OrderID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PersonContactContactID");

                    b.HasIndex("ShipCompanyCompanyID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.OrderDetail", b =>
                {
                    b.Property<long>("OrderID");

                    b.Property<long>("ProductID");

                    b.Property<double>("Price");

                    b.Property<double>("Quantity");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("Order Details");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.PersonContact", b =>
                {
                    b.Property<long>("ContactID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AddressId");

                    b.Property<long?>("CompanyID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("HomePhone")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("MobilPhone")
                        .HasMaxLength(25);

                    b.Property<string>("Title")
                        .HasMaxLength(8);

                    b.HasKey("ContactID");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyID");

                    b.ToTable("Person Contact");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CategoryID");

                    b.Property<double>("DiscontinuedPrice");

                    b.Property<long>("InStock");

                    b.Property<double>("Price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UnitName");

                    b.Property<int>("UnitScale");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.ProductCategory", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long?>("ParentCategoryCategoryID");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryCategoryID");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.Company", b =>
                {
                    b.HasOne("MigrationWithMySql.Models.AddressType", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("MigrationWithMySql.Models.PersonContact", "PrimaryContact")
                        .WithMany("Companies")
                        .HasForeignKey("PrimaryContactContactID");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.Order", b =>
                {
                    b.HasOne("MigrationWithMySql.Models.Company", "Company")
                        .WithMany("Orders")
                        .HasForeignKey("CompanyID");

                    b.HasOne("MigrationWithMySql.Models.PersonContact", "PersonContact")
                        .WithMany("Orders")
                        .HasForeignKey("PersonContactContactID");

                    b.HasOne("MigrationWithMySql.Models.Company", "ShipCompany")
                        .WithMany("ShippedOrders")
                        .HasForeignKey("ShipCompanyCompanyID");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.OrderDetail", b =>
                {
                    b.HasOne("MigrationWithMySql.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MigrationWithMySql.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MigrationWithMySql.Models.PersonContact", b =>
                {
                    b.HasOne("MigrationWithMySql.Models.AddressType", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("MigrationWithMySql.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.Product", b =>
                {
                    b.HasOne("MigrationWithMySql.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("MigrationWithMySql.Models.ProductCategory", b =>
                {
                    b.HasOne("MigrationWithMySql.Models.ProductCategory", "ParentCategory")
                        .WithMany("ChieldCategories")
                        .HasForeignKey("ParentCategoryCategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
